theme: jekyll-theme-minimal
title: Vols que Codi Cooperatiu formi part de la teva vida?
description: A Codi Cooperatiu cerquem una desenvolupadora front-end sènior que vulgui formar part de la nostra cooperativa de treball
logo: ![Logo Codi Coop] (assets/images/logo/logo_codi_coop--blanc.svg)
